server:
  port: 40000
  servlet:
    context-path: /clinical/api
spring:
  application:
    name: user-service
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      group-id: auth-login-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  datasource:
    url: jdbc:mysql://localhost:3306/clinical
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
